### ISSUE TITLE
Causes build failure on IOS

### ISSUE THREAD

**Issue by alexfigliolia** [KjellConnelly/react-native-chartboost#1]
I decided to give this library a try because it seemed like a good fit for my iOS app. Unfortunately, my build is failing since including the library. Would love some assistance 

<img width="627" alt="screen shot 2018-03-14 at 5 14 09 pm" src="https://user-images.githubusercontent.com/14042186/37431263-2787619c-27ab-11e8-9535-a42b32a09fff.png">

**Comment by KjellConnelly** [comment]
Hi Alex,

I did a quick google search and it looks like this is one of those typical Xcode issues that comes with paths and what not. Can’t debug it myself on the project I’m working on since I’m still working with RN 0.41.

Either something in my code needs to compensate for a later version of RN, or you may be able to update some of the code to fix. Check out this thread:

https://github.com/facebook/react-native/issues/15775

**Comment by alexfigliolia** [comment]
I'll make sure i have a recursive path to it. Thank you for the quick feedback!

**Comment by alexfigliolia** [comment]
Thanks for the link. Its up and running
